version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: authflow-backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://nakshatramanglik14:naksh1414@cluster0.t2jj2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=thisisnotasecretbutasafeoneistheoneintheenvfile
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - authflow-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: authflow-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://authflow-production.up.railway.app/api/v1
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - authflow-network

networks:
  authflow-network:
    driver: bridge