# railway.toml
[build]
builder = "nixpacks"
buildCommand = "cd Backend && npm install && npm run build && cd ../Frontend && npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "cd Backend && npm start & cd ../Frontend && npm start"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[[services]]
name = "backend"
healthcheck = "/health"
autoDeploy = true
port = 8000

[[services]]
name = "frontend"
healthcheck = "/"
autoDeploy = true
port = 3000