[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'cd Backend && PORT=8000 npm start & cd Frontend && PORT=3000 npm start'"
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[[ports]]
port = 3000
protocol = "tcp"

[[ports]]
port = 8000
protocol = "tcp"

[deploy.envs]
PORT = "8000"
FRONTEND_PORT = "3000"