# railway.toml
[build]
builder = "nixpacks"
buildCommand = "cd Backend && npm install && npm run build && cd ../Frontend && npm install --legacy-peer-deps && npm run build"

[[services]]
name = "backend"
dockerfile = "Backend/Dockerfile"
healthcheck = "/health"
autoDeploy = true

[[services]]
name = "frontend"
dockerfile = "Frontend/Dockerfile"
healthcheck = "/"
autoDeploy = true

[deploy]
numReplicas = 1
restartPolicyType = "on-failure"