[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'cd Backend && npm start & cd Frontend && npm start'"
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[[ports]]
port = 3000
protocol = "tcp"

[[ports]]
port = 8000
protocol = "tcp"