[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "backend"
directory = "Backend"
startCommand = "npm start"

[[services]]
name = "frontend"
directory = "Frontend"
startCommand = "npm start"