services:
  - type: web
    name: authflow-backend
    runtime: node
    buildCommand: cd Backend && npm install && npm run build
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
  - type: web
    name: authflow-frontend
    runtime: node
    buildCommand: cd Frontend && npm install && npm run build
    startCommand: cd Frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://authflow-backend.onrender.com/api/v1